version: '3.8'

services:
  app:
    build: .
    container_name: mvc_php_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: php -S 0.0.0.0:8000 -t .
    depends_on:
      - mysql

  mysql:
    image: arm64v8/mysql:8.0
    container_name: mvc_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mvc_app
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes" 
      MYSQL_ROOT_HOST: '%'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: